### ISSUE TITLE
Distinct styling for manual shortcuts

### ISSUE THREAD

**Issue by romanr** [solomkinmv/hotkys#63]
Display manual shortcuts as block of shortcuts with distinct style.

### Before:

![Arc-Notion  Hotkys-0504 0708@2x](https://github.com/solomkinmv/hotkys/assets/329079/5ddff8cf-e1a1-4d96-9a9e-dfc53f4156a0)

### After:

![Arc-Notion  Hotkys-0504 0720@2x](https://github.com/solomkinmv/hotkys/assets/329079/96288bb0-3e9f-4feb-8804-dc6e161121dc)

If this is welcome I may help with implementation.

**Comment by solomkinmv** [comment]
I think for this case I have the same concern as mentioned here: https://github.com/solomkinmv/hotkys/issues/61

This would require one more field for shortcut definition. Let's discuss this in PR #61

**Comment by romanr** [comment]
Duplicate of #61
