### ISSUE TITLE
Cmd+K for searching hotkeys is already reserved in Firefox

### ISSUE THREAD

**Issue by th0rgall** [solomkinmv/hotkys#72]
... and because of that, it opens the Firefox search engine search, instead of Hotkys' search field.

https://github.com/user-attachments/assets/45e89af8-5117-4301-a259-bd4dd781d2bb

Some thoughts:
- I could of course edit the Firefox shortcut, but that is not a sustainable solution. It would still be broken for all other Firefox users.
- Check if this Firefox behavior is not preventable, with other words, if we are allowed to override some Firefox shortcuts. Maybe there is a `preventDefault()` or similar missing somewhere? Of course, it's still a question whether it's desirable to override a default Firefox function.
- We can detect Firefox (for example using https://uaparser.dev/); and change the Hotkys shortcut in that case only to an alternative that isn't taken yet by FF.
- We can change the Hotkys search shortcut to a safer option by default.

**Comment by solomkinmv** [comment]
Oh, I didn't know about this. Can you check this site? https://developers.raycast.com/
Does CMD+K work for you here?

**Comment by th0rgall** [comment]
Good idea. Cmd+K works fine there (doesn't lose focus). So presumably it is possible to override the Firefox behavior 🙂

**Comment by solomkinmv** [comment]
Yeah, I wanted to migrate to https://github.com/pacocoursey/cmdk for this as I wanted to get "Raycast" feeling from the web

**Comment by solomkinmv** [comment]
@th0rgall please check. I think I've fixed this

**Comment by th0rgall** [comment]
@solomkinmv confirmed fixed! Thanks!
