### ISSUE TITLE
[Feature request] Allow including source information for non-link sources

### ISSUE THREAD

**Issue by th0rgall** [solomkinmv/hotkys#74]
Including a link to the source documentation that specifies shortcuts makes it easier to update the Hotkys shortcuts when they get out of date.

Documentation links are optional.

As an example, take [this metadata for Github](https://github.com/aschmelyun/use-the-keyboard/blob/36ff76b3dd8c017e31ac9f19cbdd874f3320a15b/content/github.json#L7) on [Use The Keyboard](https://usethekeyboard.com/github/), linking to the [Github shortcut docs](https://docs.github.com/en/get-started/accessibility/keyboard-shortcuts).

It could then be shown on the page for the app, similarly, like the example:

![CleanShot 2024-08-26 at 14 55 59@2x](https://github.com/user-attachments/assets/7d42fc0b-1b43-4e83-8e6a-b050ab3d1e71)

I'd be happy to make a PR for this, too.

**Comment by solomkinmv** [comment]
There's such field which is called `source`. You can check it on the [1Password](https://hotkys.com/apps/1password) page.

Also, the current design is very minimalist, so it may be hard to notice it :)
If you want to improve the UI, go on. That would be cool.

<img width="559" alt="image" src="https://github.com/user-attachments/assets/07904d21-f62d-4bd7-af5a-637ba0ce5a84">

**Comment by th0rgall** [comment]
Oh, can't believe I missed that! 🙈 That's great!

I think it works fine like this, "original reference" vs "source" is a nitpick.

One possible improvement, maybe: some apps or web apps don't have a reference web page that lists all shortcuts, but they do have a page inside the app that does the same job.

Examples are 
- [Figma](https://help.figma.com/hc/en-us/articles/360040328653-Keyboard-shortcuts-in-Figma)
- Discord (which I just added)
- FreshRSS (web app; shortcuts are shown & configurable in the app settings) and Discord (press Cmd+/).

Maybe the `source` string could also be allowed to contain plain text, like "Press Cmd+/ in Discord to show possible shortcuts".

If the source string contains a URL, it can be presented like a [Source] link as-is.

If it contains a non-URL, it could be presented like [Source ℹ️]. When you hover/click this, a little popover pops up with the information on how to find the shortcuts.

Alternatively, source could be an objects with possible values of `{type: "url", url: string }` or `{type: "in-app", info: string}`, but I think the plain string format would also just work and is simpler.

What do you think?

**Comment by solomkinmv** [comment]
The opening list of shortcuts is also a shortcut; should it be part of the source configuration?

**Comment by th0rgall** [comment]
Good point. I have indeed not found a case where such a in-app window can _not_ be opened with a shortcut. I will try to add these shortcuts where they are missing. I'm closing this with that thought.

**Comment by solomkinmv** [comment]
Feel free to reopen the issue if you have any other ideas!
